#pragma once

enum class Event {
  // Background Events
  BG_DEFAULT_SWITCH,
  BG_SHADOW_SWITCH,
  BG_CLEAR,

  // Page Switching
  MENU_MENU_SWITCH,
  LEVEL_PAGE_SWITCH,
  GAME_PAGE_SWITCH,
  GO_BACK_SWITCH,
  ABOUT_PAGE_SWITCH,
  PAUSE_PAGE_SWITCH,
  WIN_PAGE_SWITCH,
  LOSE_PAGE_SWITCH,
  QUIT,

  // Page Replaceing
  MENU_MENU_REPLACE,
  LEVEL_PAGE_REPLACE,
  GAME_PAGE_REPLACE,
  GO_BACK_REPLACE,
  ABOUT_PAGE_REPLACE,
  PAUSE_PAGE_REPLACE,
  WIN_PAGE_REPLACE,
  LOSE_PAGE_REPLACE,
};
